### ISSUE TITLE
Add ability to specify visual studio editon dependence

### ISSUE THREAD

**Issue by iccfish** [madskristensen/SolutionExtensions#12]
Some times extesnsions suggested not available or not as expect. For example if open an '.php' file in vs2015, a suggestion was shown and suggest install [PHP Language Support](https://visualstudiogallery.msdn.microsoft.com/2a10ba81-26c5-47d9-939b-6bcc7bbec251), but this extension didn't support VS2015 so it can't be installed. And I didn't want to ignore this file type due to I want to keep attention on this filetype.

It would be nice if extensions that not availble for current visual studio version are not showing.

**Comment by madskristensen** [comment]
Oh man, can't believe I missed that. Thanks for reporting the issue

**Comment by madskristensen** [comment]
Since the extension can only work on vS2015 I don't think this would be of much value.
