### ISSUE TITLE
Part of .NET Core Tooling Preview now?

### ISSUE THREAD

**Issue by gentoo90** [madskristensen/SolutionExtensions#19]
Or is going to be?

Tooling Preview now suggests to install some extensions when I open a file:
![vsext](https://cloud.githubusercontent.com/assets/1297574/15815863/47d97d84-2bd8-11e6-9d23-ed07fd3fca91.png)

But when I create `*.vsext` file, nothing happens, the suggestion dialog doesn't appear.

**Comment by madskristensen** [comment]
You still need this extension for that to work. Web Tooling Preview doesn't contain all of what this extension does -far from it.

**Comment by madskristensen** [comment]
You still need this extension for that to work. Web Tooling Preview doesn't contain all of what this extension does -far from it.

**Comment by sindilevich** [comment]
@madskristensen, do `*.vsext` files require to be source-controlled, or it is perfectly safe to place them in `.gitignore`/`.hgignore` in a multi-people development environment?

**Comment by madskristensen** [comment]
Yes, I would check them in to make sure that everyone on your team gets them. Otherwise it would be only you

**Comment by sindilevich** [comment]
@madskristensen, thank you!
