### ISSUE TITLE
Support VS 2013 and suggest by VS versions

### ISSUE THREAD

**Issue by ChrisTorng** [madskristensen/SolutionExtensions#2]
Please support VS 2013. Because not every extensions are all available in 2013/2015, and not exactly they are the same id, so please suggest by VS versions. Maybe you need to have `(solution).v12.vsext` and `(solution).v14.vsext`. Then I can suggest Web Essentials in 2013, but Web Compiler + Bundler & Minifier in 2015.

**Comment by madskristensen** [comment]
I can't do that without creating a separate extension for VS2013 due to differences in the APIs this extension is using. I don't want to maintain 2 extensions for this, so unfortunately this can't happen

**Comment by yannduran** [comment]
I don't need a VS 2103 version personally, but wouldn't all it take is to just have the extension query the  version of VS it's installed in, then look up a version specific section in the suggestions.json file?

This would also "future-proof" the extension as well, so when the vNext arrives, all it would take to be compatible would be a new section in suggestions.json.
