### ISSUE TITLE
Visual Studio 2017 support

### ISSUE THREAD

**Issue by Sc0tTyXL** [madskristensen/SolutionExtensions#24]
The extension is not available for VS 2017.
Could you add support for it ?

Would really like to add some "required extensions" to our projects: http://stackoverflow.com/questions/44071335/visual-studio-extension-dependency

**Comment by ErikEJ** [comment]
@Sc0tTyXL You could just clone it?

**Comment by ErikEJ** [comment]
Duplicate of #15 btw

**Comment by Sc0tTyXL** [comment]
Ah I didn't realize 15 and 2017 were the same version.

**Comment by Thieum** [comment]
[This newer extension](https://github.com/madskristensen/ExtensionPackTools) has the part where you can "bind" extensions to a solution.

**Comment by Sc0tTyXL** [comment]
I guess this issue can be closed now
