### ISSUE TITLE
Modal Dialog Box Should Be Modal to VS

### ISSUE THREAD

**Issue by yannduran** [madskristensen/SolutionExtensions#3]
When opening a solution, after installing this extension, a modal dialog box appears for the suggested mandatory and optional extensions for that solution. However if you happen to switch to a different application before closing the dialog box, it stays on top of the other application.

I discovered this issue because I wanted to open a browser to research one of the suggested extensions before I allowed it to be installed. This is probably something people will do. Even when the browser window is maximised, the dialog box sits on top it, whereas it should only be visible when Visual Studio has focus.

It also would be great to have a built-in way to view details about a suggested extension, right from the list of extensions, but I'll add a suggestion for that separately.

Here is an image showing the problem:
![image](https://cloud.githubusercontent.com/assets/2031126/9489151/39c04cdc-4c22-11e5-9f37-cd5a8ddcec7b.png)

**Comment by madskristensen** [comment]
Fixed

**Comment by ErikEJ** [comment]
Why not use DialogWindow?
