### ISSUE TITLE
Adding existing .sdf files does not prompt suggestion, as expected

### ISSUE THREAD

**Issue by ErikEJ** [madskristensen/SolutionExtensions#8]
On a .NET 4.5 console app, adding an existing item .sdf file (and even opening it afterwards) does not trigger any suggestions. I have build 39 installed.

Adding a test.db or even a test.sdf via Add/New Item file correctly triggers extensions suggestions a well - I think the problem might be that the extension only checks for text creation event rather than the event of a new item being added to the project?  (Opening a sdf file already in the project opens it in the hex editor, not  text view)

**Comment by madskristensen** [comment]
That's right. The extension only triggers when a file is being opened

**Comment by ErikEJ** [comment]
Would be great if it also responded to project items being added

**Comment by madskristensen** [comment]
Yeah, and NuGet/Bower/NPM packages being installed.

**Comment by ErikEJ** [comment]
Great!
