### ISSUE TITLE
Support more levels/scopes of Suggested Extensions

### ISSUE THREAD

**Issue by DavidDeSloovere** [madskristensen/SolutionExtensions#9]
A global suggestion list is great. Solution specific extensions also. But I'd like to see something in between.

For example **suggested extensions scoped to a "team"**. That way we don't have to repeat extensions in the .vsext file again and again. 
The **.json file** can be retrieved via **HTTP(S)**. That way Github Gists are covered. But probably also OneDrive, Dropbox via a share link.

Other scopes aside from _Team_ could be _Company_ or _User_.

PS: User level might not be needed, because there's the Roaming Extension Manager.

**Comment by madskristensen** [comment]
Yes! This is coming...

**Comment by yannduran** [comment]
+1, great idea!
